name: Linux Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: swift:6.2.0
    steps:
      - uses: actions/checkout@v4

      - name: Install libgd
        run: apt-get update && apt-get install -y libgd-dev

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
